### PR TITLE
workflows: Update actions

### PR DESCRIPTION
**Pull request by sarthakroy2002**
- Update actions/checkout to v3
- Update actions/setup-go to v3

### CODE REVIEW

**Comment by kevinfalting** [comment]
Hey @sarthakroy2002, thanks for the MR. I'm not super familiar with github actions and this change. Can you describe what's going on here and why it's needed? Thanks. ❤️

**Comment by sarthakroy2002** [comment]
> Hey @sarthakroy2002, thanks for the MR. I'm not super familiar with github actions and this change. Can you describe what's going on here and why it's needed? Thanks. ❤️

Hey,

So it updates the action dependencies to latest version. It includes various bug fixes and feature updates. Its always advised to keep actions up to date.

**Comment by kevinfalting** [comment]
Thanks. Do you have recommended testing steps? I haven't seen the change log to be sure the update maintains backward compatibility.

**Comment by sarthakroy2002** [comment]
> Thanks. Do you have recommended testing steps? I haven't seen the change log to be sure the update maintains backward compatibility.

It shouldnt break anything. Well testing steps are same as deploying it. 

https://github.com/actions/setup-go
https://github.com/actions/checkout

you can check the changelogs here.

**Review by kevinfalting — APPROVED** [review]

**Pull request merged**
